# Generated by Django 3.1.5 on 2021-01-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='platforms.route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='platform_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='platforms.platform'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='platforms.route'),
        ),
    ]
