# Generated by Django 3.1.5 on 2021-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_auto_20210128_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='image',
            field=models.ImageField(default='platformImage', upload_to='platformImages'),
        ),
    ]
